# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Status'
description: "GitHub Action to check Docker system status in your workflow"
author: 'crazy-max'
branding:
  color: 'orange'
  icon: 'alert-triangle'

inputs:
  overall_threshold:
    description: 'Defines threshold for overall status (also called rollup) of Docker to fail the job'
    required: false
  hub_registry_threshold:
    description: 'Defines threshold for Docker Hub Registry to fail the job'
    required: false
  authentication_threshold:
    description: 'Defines threshold for Docker Authentication to fail the job'
    required: false
  hub_web_threshold:
    description: 'Defines threshold for Docker Hub Web to fail the job'
    required: false
  desktop_threshold:
    description: 'Defines threshold for Docker Desktop to fail the job'
    required: false
  billing_threshold:
    description: 'Defines threshold for Docker Billing to fail the job'
    required: false
  package_repositories_threshold:
    description: 'Defines threshold for Docker Package Repositories to fail the job'
    required: false
  hub_automated_builds_threshold:
    description: 'Defines threshold for Docker Hub Automated Builds to fail the job'
    required: false
  hub_security_scanning_threshold:
    description: 'Defines threshold for Docker Hub Security Scanning to fail the job'
    required: false
  docs_threshold:
    description: 'Defines threshold for Docker Docs to fail the job'
    required: false
  community_forums_threshold:
    description: 'Defines threshold for Docker Community Forums to fail the job'
    required: false
  support_site_threshold:
    description: 'Defines threshold for Docker Support to fail the job'
    required: false
  web_threshold:
    description: 'Defines threshold for Docker.com Website to fail the job'
    required: false
  scout_threshold:
    description: 'Defines threshold for Docker Scout to fail the job'
    required: false
  build_cloud_threshold:
    description: 'Defines threshold for Docker Build Cloud to fail the job'
    required: false
  testcontainers_cloud_threshold:
    description: 'Defines threshold for Testcontainers Cloud to fail the job'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
